name: PostEra's self-hosting of Font Awesome's "regular" icon set

on:
  release:
    types: [created]

jobs:
  publish-gpr:
    runs-on: ['x64', 'self-hosted', 'shared-resources', 'linux', 'general']
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build:core
      - run: npm publish -workspaces
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}